# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MWwmymTsNI_RM_baCZ8qOlzt0KxInVCf
"""

# Patron Strategy 
# objetivo tener diferentes logica sencapsuladas , se crean objetos que represntan estas estrategias : siguen un patron = impelemntan interfaz o s eusan d eclase abstracta-> polimorfismo
# contexto = funcion o clase que usa las estrategias , interfaz define las firmas o funciones e implementa las funcionalidades

def calcular( nombreEstrategia,numUno,numDos):
  def suma():
    return numUno + numDos
  def resta():
    return numUno - numDos
  def multiplicacion():
    return numUno * numDos
  def division():
    return numUno / numDos

    # agrupar en un diccionario
  
  operaciones = {
      'suma': suma,
      'resta' : resta,
      'multiplicacion' : multiplicacion,
      'division' : division
  }

  if nombreEstrategia in operaciones:
    return operaciones[nombreEstrategia]()
  else:
    return None
  


def main():
  resultado = calcular('resta', 5 , 4)
  print(resultado)

main()

def suma(numUno,numDos):
  return numUno + numDos

def resta(numUno,numDos):
  return numUno - numDos

operaciones = {
      'suma': suma,
      'resta' : resta
      }

   
def calcular(nombreEstrategia,numUno,numDos):
  if nombreEstrategia in operaciones:
    return operaciones[nombreEstrategia](numUno,numDos)
  else:
    return None
  


def main():
  resultado = calcular('resta', 5 , 4)
  print(resultado)

main()

