# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/191EXt1lvdPO0ER0WV9zntnvOUC7Smp0j
"""

arr = ["amarillo","verde","azul","azul","azul","amarillo","verde","gris","azul","gris"]

yaEsta = []
flag = 0

for i in range(len(arr)):
  
  if len(yaEsta) == 0:
    yaEsta.append(arr[i])
  
  else:
    for j in range(len(yaEsta)):
      if arr[i] != yaEsta[j] :
        flag = 0 # es un elemento unico
      else:
        flag = 1

    if flag == 0:
      yaEsta.append(arr[i])
         
print(yaEsta)

#___________________________________________________________________________________________
# eliminar duplicados contiguos

arr = ["amarillo","verde","azul","azul","azul","amarillo","verde","gris","azul","gris"]

noDuplicates = []


for i in range(len(arr) - 1):
  if i < len(arr )  :
    if arr[i] != arr[i + 1]:
      noDuplicates.append(arr[i])
    
print(noDuplicates )

#________________________________________________________________________________

arr = ["amarillo","verde","azul","azul","azul","amarillo","verde","gris","azul","gris"]

# primero quitar repetidos contiguos
noDuplicates = []

for i in range(len(arr) - 1):
  if i < len(arr )  :
    if arr[i] != arr[i + 1]:
      noDuplicates.append(arr[i])
    
arr = noDuplicates

print(arr)
#__ quitar repetidos no contiguos

yaEsta = []
flag = 0
contador = 0
for i in range(len(arr)):
  # el primer elemento se anade
  if len(yaEsta) == 0:
    yaEsta.append(arr[i])
  else:
    # verificar si el elemnto i esta en la lista, si no se agrega al yaEsta
    for j in range(i,len(arr)):
      print(i,j, arr[i] , arr[j])

      
        
  
    print("___________________________")

#________________________________________________________________________________

arr = ["amarillo","verde","azul","azul","azul","amarillo","verde","gris","azul","gris"]

# primero quitar repetidos contiguos
noDuplicates = []

for i in range(len(arr) - 1):
  if i < len(arr )  :
    if arr[i] != arr[i + 1]:
      noDuplicates.append(arr[i])
    
arr = noDuplicates

print(arr)
#__ quitar repetidos no contiguos

yaEsta = []
flag = 0
contador = 0
for i in range(len(arr)):
  # el primer elemento se anade
  if len(yaEsta) == 0:
    yaEsta.append(arr[i])
  else:
    # verificar si el elemnto i esta en la lista, si no se agrega al yaEsta
    for j in range(i,len(arr)):
      if i != j:
        print(i,j, arr[i] , arr[j])

      
        
  
    print("___________________________")

#________________________________________________________________________________

arr = ["amarillo","verde","azul","azul","azul","amarillo","verde","gris","azul","gris"]

# primero quitar repetidos contiguos
noDuplicates = []

for i in range(len(arr) - 1):
  if i < len(arr )  :
    if arr[i] != arr[i + 1]:
      noDuplicates.append(arr[i])
    
arr = noDuplicates

print(arr)
#__ quitar repetidos no contiguos

yaEsta = []
flag = 0
contador = 0
for i in range(len(arr)):
  # el primer elemento se anade
  if len(yaEsta) == 0:
    yaEsta.append(arr[i])
  else:
    # verificar si el elemnto i esta en la lista, si no se agrega al yaEsta
    if i == 1 :
      # esta accion solo se ejecuta una vez
      for j in range(i,len(arr)):
        if i != j:
          print(i,j, arr[i] , arr[j])
          yaEsta.append(arr[j])
     
        
  
print(yaEsta)

#________________________________________________________________________________

arr = ["amarillo","verde","azul","azul","azul","amarillo","verde","gris","azul","gris"]

# primero quitar repetidos contiguos
noDuplicates = []

for i in range(len(arr) - 1):
  if i < len(arr )  :
    if arr[i] != arr[i + 1]:
      noDuplicates.append(arr[i])
    
arr = noDuplicates

print(arr)
#__ quitar repetidos no contiguos

yaEsta = []
flag = 0 
contador = 0
for i in range(len(arr)):
  if i == 0: # elimino repetidos respecto al primero
    for j in range(i,len(arr)):
      if i != j:
        print(i,j, arr[i] , arr[j])
        yaEsta.append(arr[j])
  
      
  
print(yaEsta)

#________________________________________________________________________________

arr = ["amarillo","verde","azul","azul","azul","amarillo","verde","gris","azul","gris"]

# primero quitar repetidos contiguos
noDuplicates = []

for i in range(len(arr) - 1):
  if i < len(arr )  :
    if arr[i] != arr[i + 1]:
      noDuplicates.append(arr[i])
    
arr = noDuplicates

print(arr)
#__ quitar repetidos no contiguos

repetidoCero = []
repetidoUno = []
noRepetido=[]
flag = 0 
contador = 0
for i in range(len(arr)):
  if i == 0: # elimino repetidos respecto al primero
    for j in range(i,len(arr)):
      print(i,j, arr[i] , arr[j])
      if i != j and arr[i] == arr[j]:
        flag = 1 # se encuentra repetido de manera no contigua 
    if flag == 0 : 
      # si el elemnto es unico, anado el elemento de referencia/comparacion
      noRepetido.append(arr[i])


  
      
  
print(noRepetido)

# pythonic way__________________________________________________________________
arr = ["amarillo","verde","azul","azul","azul","amarillo","verde","gris","azul","gris"]
noRepetidos = []

for i in range(len(arr)):
  if arr[i] not in noRepetidos:
    print(arr[i])
    noRepetidos.append(arr[i])

print(norepetidos)

# pythonic way__________________________________________________________________
arr = ["amarillo","verde","azul","azul","azul","amarillo","verde","gris","azul","gris"]
noRepetidos = []

for i in range(len(arr)):
  print(i)
  if arr[i] not in noRepetidos:
    print(arr[i])
    noRepetidos.append(arr[i])

print(norepetidos)

