# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vNKl92iL-jCbyEEM2mcdV9CsYsp93NZR
"""

# remove duplicate elements 

arreglo = [1,1,2,4,5,7,7,7,8,9]  # sorted 
rta = [] 

print(len(arreglo))

for i in range(len(arreglo) ):
  if i < len(arreglo )  :
    if arreglo[i] != arreglo[i + 1]:
      rta.append(arreglo[i])
    
print(rta)