# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VxT4sNGD-cQDCMSEt1ftIt_qDAgTnNgX
"""

# linear algorithms

# encontrar el maximo 

import random
menor = 0
mayor= 99
cantidad = 150

random.seed(10)

arreglo = [random.randint(menor, mayor) for iter in range(cantidad )]
print(arreglo)
 
maximo = 0  # mayor - 1
for i in range(len(arreglo)):
  if maximo < arreglo[i]:
    maximo = arreglo[i]
print(maximo)

# encontrar el segundo maximo 
import random
menor = 0
mayor= 99
cantidad = 150

random.seed(10)

arreglo = [random.randint(menor, mayor) for iter in range(cantidad )]
print(arreglo)
 
maximo = 0  # mayor - 1
antiguoMax = 0
for i in range(len(arreglo)):
  if maximo < arreglo[i]:
    antiguoMax = maximo
    maximo = arreglo[i]
    print(maximo,antiguoMax)
print(maximo,antiguoMax)

# encontrar el segundo maximo 
import random
menor = 0
mayor= 99
cantidad = 150

random.seed(10)

arreglo = [random.randint(menor, mayor) for iter in range(cantidad )]
print(arreglo)
 
maximo = 0  # mayor - 1

for i in range(len(arreglo)):
  if maximo < arreglo[i]:
    maximo = arreglo[i]
    
antiguoMax = 0
for i in  range(len(arreglo)):
  if arreglo[i] != maximo:
    if antiguoMax < arreglo[i]:
      antiguoMax = arreglo[i]
      print(maximo,antiguoMax)
print(maximo,antiguoMax) 

# corregir aplicando indice

# sums on subsegment

